---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: NetworkPolicy validations
templates:
  - common.yaml
values:
  - ../_values/components_main_default_container.yaml
tests:
  - it: networkpolicy requires either component reference or podSelector
    set:
      networkpolicies:
        main:
          component: ""
          rules: {}
    asserts:
      - failedTemplate:
          errorMessage: "component reference or podSelector is required for NetworkPolicy. (NetworkPolicy main)"

  - it: policyTypes is required
    set:
      networkpolicies:
        main:
          component: main
          policyTypes: []
          rules: {}
    asserts:
      - failedTemplate:
          errorMessage: "policyTypes is required for NetworkPolicy. (NetworkPolicy main)"

  - it: policyTypes values check
    set:
      networkpolicies:
        main:
          component: main
          policyTypes:
            - test
          rules: {}
    asserts:
      - failedTemplate:
          errorMessage: "Not a valid policyType for NetworkPolicy. (NetworkPolicy main, value test)"
