---




---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME
  namespace: NAMESPACE
  labels:
    app.kubernetes.io/component: main
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: RELEASE-NAME
    helm.sh/chart: common-test-1.0.0
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/component: main
      app.kubernetes.io/name: RELEASE-NAME
      app.kubernetes.io/instance: RELEASE-NAME
  template:
    metadata:
      labels: 
        app.kubernetes.io/component: main
        app.kubernetes.io/instance: RELEASE-NAME
        app.kubernetes.io/name: RELEASE-NAME
    spec: 
      enableServiceLinks: false
      serviceAccountName: default
      automountServiceAccountToken: true
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      topologySpreadConstraints: 
          - labelSelector:
              matchLabels:
                app: foo
            maxSkew: 2
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: DoNotSchedule
      containers: 
        - image: ghcr.io/mendhak/http-https-echo:31
          imagePullPolicy: IfNotPresent
          name: main








