---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: secret metadata
templates:
  - common.yaml
values:
  - ../_values/components_main_default_container.yaml
tests:
  - it: default metadata should pass
    set:
      externalsecrets:
        externalsecret:
          data:
          - secretKey: username
            remoteRef:
              key: database-credentials
          # secretStoreRef:
          #   kind: ClusterSecretStore
          #   name: cluster-secret-store
          # data:
          # - secretKey: username
          #   remoteRef:
          #     key: database-credentials
          #     version: v1
          #     property: username
          #     # decodingStrategy: None # can be None, Base64, Base64URL or Auto
    asserts:
      - hasDocuments:
          count: 2
      - documentIndex: &SecretDocument 1
        isKind:
          of: ExternalSecret
      - documentIndex: *SecretDocument
        notExists:
          path: metadata.annotations
      - documentIndex: *SecretDocument
        equal:
          path: metadata.labels
          value:
            app.kubernetes.io/instance: RELEASE-NAME
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: RELEASE-NAME
            app.kubernetes.io/version: 1.0.0
            helm.sh/chart: common-test-1.0.0
  - it: custom metadata should pass
    set:
      externalsecrets:
        externalsecret:
          annotations:
            test_annotation: test
          labels:
            test_label: test
          data:
          - secretKey: username
            remoteRef:
              key: database-credentials
    asserts:
      - hasDocuments:
          count: 2
      - documentIndex: &SecretDocument 1
        isKind:
          of: ExternalSecret
      - documentIndex: *SecretDocument
        equal:
          path: metadata.annotations
          value:
            test_annotation: test
      - documentIndex: *SecretDocument
        equal:
          path: metadata.labels
          value:
            app.kubernetes.io/instance: RELEASE-NAME
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: RELEASE-NAME
            app.kubernetes.io/version: 1.0.0
            helm.sh/chart: common-test-1.0.0
            test_label: test

  - it: custom metadata with global metadata should pass
    set:
      global:
        labels:
          global_label: test
        annotations:
          global_annotation: test
      externalsecrets:
        externalsecret:
          annotations:
            test_annotation: test
          labels:
            test_label: test
          data:
          - secretKey: username
            remoteRef:
              key: database-credentials
    asserts:
      - hasDocuments:
          count: 2
      - documentIndex: &SecretDocument 1
        isKind:
          of: ExternalSecret
      - documentIndex: *SecretDocument
        equal:
          path: metadata.annotations
          value:
            global_annotation: test
            test_annotation: test
      - documentIndex: *SecretDocument
        equal:
          path: metadata.labels
          value:
            app.kubernetes.io/instance: RELEASE-NAME
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: RELEASE-NAME
            app.kubernetes.io/version: 1.0.0
            global_label: test
            helm.sh/chart: common-test-1.0.0
            test_label: test
