---
apiVersion: v2
description: A common powered chart template. This can be useful for small projects that don't have their own chart.
name: app-template
version: 4.15.2
kubeVersion: ">=1.22.0-0"
maintainers:
  - name: FLYR-Open-Source
    email: david.vanderspek@flyr.com
dependencies:
  - name: common
    repository: oci://ghcr.io/flyr-open-source/helm
    version: 4.15.3
sources:
  - https://github.com/FLYR-Open-Source/helm-library-chart
annotations:
  artifacthub.io/changes: |-
    - kind: fixed
      description: |-
        Fixed name suffix for HTTPRoute
    - kind: fixed
      description: |-
        Fixed incorrect default backendRefs values in HTTPRoute
