---
apiVersion: v2
name: common
description: Function library for Helm charts
type: library
version: 4.15.2
kubeVersion: ">=1.22.0-0"
keywords:
  - common
  - library
home: https://github.com/FLYR-Open-Source/helm-library-charts/tree/main/charts/library/common
maintainers:
  - name: David van der Spek
    email: david.vanderspek@flyr.com
sources:
  - https://github.com/FLYR-Open-Source/helm-library-chart
annotations:
  artifacthub.io/changes: |-
    - kind: fixed
      description: |-
        Publish to new fork
