---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: persistence custom
templates:
  - common.yaml
values:
  - ../_values/components_main_default_container.yaml
tests:
  - it: custom persistence type should pass
    set:
      persistence:
        custom-mount:
          enabled: true
          type: custom
          volumeSpec:
            downwardAPI:
              items:
                - path: "labels"
                  fieldRef:
                    fieldPath: metadata.labels
    asserts:
      - documentIndex: 0
        isKind:
          of: Deployment
      - documentIndex: 0
        equal:
          path: spec.template.spec.volumes[0]
          value:
            name: custom-mount
            downwardAPI:
              items:
                - fieldRef:
                    fieldPath: metadata.labels
                  path: labels

  - it: custom persistence type with template should pass
    set:
      onlyDir: test-dir
      persistence:
        custom-mount:
          enabled: true
          type: custom
          volumeSpec:
            name: gcs
            csi:
              driver: gcsfuse.csi.storage.gke.io
              readOnly: false
              volumeAttributes:
                bucketName: test
                mountOptions: "rename-dir-limit=1000,uid=981,gid=981,implicit-dirs,only-dir={{ .Values.onlyDir }},o=disable_hardlink"
                gcsfuseLoggingSeverity: warning
    asserts:
      - documentIndex: 0
        isKind:
          of: Deployment
      - documentIndex: 0
        equal:
          path: spec.template.spec.volumes[0]
          value:
            name: custom-mount
            csi:
              driver: gcsfuse.csi.storage.gke.io
              readOnly: false
              volumeAttributes:
                bucketName: test
                mountOptions: "rename-dir-limit=1000,uid=981,gid=981,implicit-dirs,only-dir=test-dir,o=disable_hardlink"
                gcsfuseLoggingSeverity: warning
