---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: component metadata job
templates:
  - common.yaml
values:
  - ../_values/components_main_default_container.yaml
tests:
  - it: default metadata should pass
    set:
      components.main.type: job
    asserts:
      - documentIndex: &ComponentDoc 0
        isKind:
          of: Job
      - documentIndex: *ComponentDoc
        notExists:
          path: metadata.annotations
      - documentIndex: *ComponentDoc
        equal:
          path: metadata.labels
          value:
            app.kubernetes.io/component: main
            app.kubernetes.io/instance: RELEASE-NAME
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: RELEASE-NAME
            app.kubernetes.io/version: 1.0.0
            helm.sh/chart: common-test-1.0.0

  - it: custom metadata should pass
    set:
      components:
        main:
          type: job
          annotations:
            test_annotation: test
          labels:
            test_label: test
    asserts:
      - documentIndex: &ComponentDoc 0
        isKind:
          of: Job
      - documentIndex: *ComponentDoc
        equal:
          path: metadata.annotations
          value:
            test_annotation: test
      - documentIndex: *ComponentDoc
        equal:
          path: metadata.labels
          value:
            app.kubernetes.io/component: main
            app.kubernetes.io/instance: RELEASE-NAME
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: RELEASE-NAME
            app.kubernetes.io/version: 1.0.0
            helm.sh/chart: common-test-1.0.0
            test_label: test

  - it: custom metadata with global metadata should pass
    set:
      global:
        labels:
          global_label: test
        annotations:
          global_annotation: test
      components:
        main:
          type: job
          annotations:
            test_annotation: test
          labels:
            test_label: test
    asserts:
      - documentIndex: &ComponentDoc 0
        isKind:
          of: Job
      - documentIndex: *ComponentDoc
        equal:
          path: metadata.annotations
          value:
            global_annotation: test
            test_annotation: test
      - documentIndex: *ComponentDoc
        equal:
          path: metadata.labels
          value:
            app.kubernetes.io/component: main
            app.kubernetes.io/instance: RELEASE-NAME
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: RELEASE-NAME
            app.kubernetes.io/version: 1.0.0
            global_label: test
            helm.sh/chart: common-test-1.0.0
            test_label: test

  - it: jobTemplate metadata should pass
    set:
      components:
        main:
          type: job
          pod:
            annotations:
              test_annotation: test
            labels:
              test_label: test
    asserts:
      - documentIndex: &ComponentDoc 0
        isKind:
          of: Job
      - documentIndex: *ComponentDoc
        equal:
          path: spec.template.metadata.annotations
          value:
            test_annotation: test
      - documentIndex: *ComponentDoc
        equal:
          path: spec.template.metadata.labels
          value:
            app.kubernetes.io/component: main
            app.kubernetes.io/instance: RELEASE-NAME
            app.kubernetes.io/name: RELEASE-NAME
            app.kubernetes.io/version: 1.0.0
            test_label: test
