---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: component types
templates:
  - common.yaml
values:
  - ../_values/components_main_default_container.yaml
tests:
  - it: default should pass
    asserts:
      - documentIndex: &deploymentDoc 0
        isKind:
          of: Deployment
      - documentIndex: *deploymentDoc
        equal:
          path: metadata.name
          value: RELEASE-NAME
      - documentIndex: *deploymentDoc
        equal:
          path: metadata.labels['app.kubernetes.io/component']
          value: main

  - it: additional components should pass
    set:
      components:
        second:
          containers:
            main:
              image:
                repository: ghcr.io/mendhak/http-https-echo
                tag: 31
    asserts:
      - hasDocuments:
          count: 2
      - documentIndex: &firstDeploymentDoc 0
        isKind:
          of: Deployment
      - documentIndex: *firstDeploymentDoc
        equal:
          path: metadata.name
          value: RELEASE-NAME-main
      - documentIndex: *firstDeploymentDoc
        equal:
          path: metadata.labels['app.kubernetes.io/component']
          value: main
      - documentIndex: &secondDeploymentDoc 1
        isKind:
          of: Deployment
      - documentIndex: *secondDeploymentDoc
        equal:
          path: metadata.name
          value: RELEASE-NAME-second
      - documentIndex: *secondDeploymentDoc
        equal:
          path: metadata.labels['app.kubernetes.io/component']
          value: second

  - it: additional components with nameOverride should pass
    set:
      components:
        main:
          nameOverride: "{{ .Release.Name }}"
        second:
          nameOverride: testOverride
          containers:
            main:
              image:
                repository: ghcr.io/mendhak/http-https-echo
                tag: 31
    asserts:
      - hasDocuments:
          count: 2
      - documentIndex: &firstDeploymentDoc 0
        isKind:
          of: Deployment
      - documentIndex: *firstDeploymentDoc
        equal:
          path: metadata.name
          value: RELEASE-NAME
      - documentIndex: *firstDeploymentDoc
        equal:
          path: metadata.labels['app.kubernetes.io/component']
          value: main
      - documentIndex: &secondDeploymentDoc 1
        isKind:
          of: Deployment
      - documentIndex: *secondDeploymentDoc
        equal:
          path: metadata.name
          value: RELEASE-NAME-testOverride
      - documentIndex: *secondDeploymentDoc
        equal:
          path: metadata.labels['app.kubernetes.io/component']
          value: second

  - it: daemonset should pass
    set:
      components.main.type: daemonset
    asserts:
      - documentIndex: &ComponentDoc 0
        isKind:
          of: DaemonSet
      - documentIndex: *ComponentDoc
        equal:
          path: metadata.name
          value: RELEASE-NAME

  - it: statefulset should pass
    set:
      components.main.type: statefulset
    asserts:
      - documentIndex: &ComponentDoc 0
        isKind:
          of: StatefulSet
      - documentIndex: *ComponentDoc
        equal:
          path: metadata.name
          value: RELEASE-NAME

  - it: cronjob should pass
    set:
      components.main.type: cronjob
      components.main.cronjob.schedule: "*/20 * * * *"
    asserts:
      - documentIndex: &ComponentDoc 0
        isKind:
          of: CronJob
      - documentIndex: *ComponentDoc
        equal:
          path: metadata.name
          value: RELEASE-NAME

  - it: disabled should pass
    set:
      components.main.enabled: false
    asserts:
      - hasDocuments:
          count: 0
