---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: configmap Pod metadata
templates:
  - common.yaml
values:
  - ../_values/components_main_default_container.yaml
tests:
  - it: default metadata should pass
    set:
      configMaps:
        config:
          enabled: true
          data:
            test: value 1
        test_default_enabled:
          data:
            test: value 1
        test_not_in_checksum:
          includeInChecksum: false
          data:
            test: value 1
        test_disabled:
          enabled: false
          data:
            test: value 1
    asserts:
      - documentIndex: &ComponentDoc 3
        isKind:
          of: Deployment
      - documentIndex: *ComponentDoc
        equal:
          path: spec.template.metadata.annotations
          value:
            checksum/configMaps: 66d23d7a53c4e2a523ba85a969696b4ebb78ec5d79ab9c12c210c1569f48511b

  - it: default metadata from folder should pass
    set:
      configMaps:
        config:
          enabled: true
          data:
            test: value 1
        test_default_enabled:
          data:
            test: value 1
        test_not_in_checksum:
          includeInChecksum: false
          data:
            test: value 1
        test_disabled:
          enabled: false
          data:
            test: value 1
      configMapsFromFolder:
        enabled: true
        basePath: ci/configMapsFolder
        configMapsOverrides:
          test_2:
            fileAttributeOverrides:
              helm.jpg:
                binary: true
              test_2.yaml:
                escaped: true
    asserts:
      - documentIndex: &ComponentDoc 5
        isKind:
          of: Deployment
      - documentIndex: *ComponentDoc
        equal:
          path: spec.template.metadata.annotations
          value:
            checksum/configMaps: 07082ebad65585af1d6a8fb597e828ed892e3a8080d80debf6e1e695cea7a57c

  - it: templated metadata should pass
    set:
      configMaps:
        config:
          enabled: true
          data:
            test: |
              {{- include "template.test" . | nindent 2 }}
    asserts:
      - documentIndex: &ComponentDoc 1
        isKind:
          of: Deployment
      - documentIndex: *ComponentDoc
        equal:
          path: spec.template.metadata.annotations
          value:
            checksum/configMaps: 464ff2b4da8069feb1eb729e47c433556de95e7a9887c091450fa5300b4b5fc6
      - documentIndex: &ConfigMapDoc 0
        isKind:
          of: ConfigMap
      - documentIndex: *ConfigMapDoc
        equal:
          path: data.test
          value: |
            nested:
              key: value 1
              key2: value 2
              key3:
                key4: value 4
