name: "Docs: Release to GitHub pages"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/docs-release.yaml"
      - ".ci/mkdocs/mkdocs.yml"
      - "docs/**"

permissions:
  contents: write

jobs:
  release-docs:
    name: Release documentation
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install requirements
        run: pip install -r docs/requirements.txt

      - name: Build and publish docs
        run: mkdocs build -f .ci/mkdocs/mkdocs.yml

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          destination_dir: docs
          user_name: "davidspek-bot[bot]"
          user_email: "davidspek-bot <87358111+davidspek-bot[bot]@users.noreply.github.com>"
