name: "Charts: Create git tag"

on:
  workflow_call:
    inputs:
      charts:
        description: >
          Json encoded list of Helm charts to release.
          Defaults to releasing everything.
        default: "[]"
        required: false
        type: string

permissions:
  contents: write
  actions: read

env:
  CHARTS_SRC_DIR: "charts"

jobs:
  tag-charts:
    name: Tag charts
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout chart sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create git tag for charts
        shell: bash
        run: |
          CHARTS=( $(yq --null-input e '${{ inputs.charts }}[]' ) )

          for CHART in "${CHARTS[@]}" ; do
            mapfile -t CHART_PATH_PARTS < <(echo "$CHART" | tr '/' '\n')
            CHART_TYPE=${CHART_PATH_PARTS[0]}
            CHART_NAME=${CHART_PATH_PARTS[1]}
            CHART_VERSION=$(yq e '.version' ${{ env.CHARTS_SRC_DIR }}/${CHART}/Chart.yaml)

            git tag --force "${CHART_NAME}-${CHART_VERSION}"
          done

          git push --tags --force
